server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/payment/**
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/inventory/**
        - id: shipping-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/shipping/**


resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  retry:
    instances:
      paymentService:
        maxRetryAttempts: 3
        waitDuration: 2s
  timelimiter:
    instances:
      paymentService:
        timeoutDuration: 3s

